permalink: /:year-:month-:day/:title
url: http://github.com/holajun
baseurl: ""

# variables
name: HolaJun
description: helloworld
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
